### ISSUE TITLE
Readme API Reference

### ISSUE THREAD

**Issue by LloydThinks** [OpenReqEU/mallikas#1]
Please update the API link in your readme.

Old: https://api.openreq.eu/mallikas/swagger-ui.html
New: https://api.openreq.eu/#/services/mallikas

The new link is much more user friendly, the the link they will be directed to by the UI should they go looking for it themselves.

Lloyd

**Comment by mzraatik** [comment]
Fixed in release branch. This will be updated when we update the master.
